version: "3"
services:
  orthanc:
    image: jodogne/orthanc-plugins:1.10.1
    hostname: orthanc
    volumes:
      - ./.docker/Nginx-Orthanc/config/orthanc.json:/etc/orthanc/orthanc.json:ro
      - ./.docker/Nginx-Orthanc/volumes/orthanc-db/:/var/lib/orthanc/db/
    ports:
      - '4242:4242' # DICOM
      - '8042:8042' # Web
    restart: always

  ohif_viewer:
    build:
      context: .
      dockerfile: Dockerfile
    image: ohif_viewer
    ports:
      - 3000:80
    environment:
      - APP_CONFIG:/usr/share/nginx/html/app-config.js
    restart: always
